apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonar
  # namespace: jenkins 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
          name: sonarqube
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: sonar
  # namespace: jenkins 
spec:
  type: LoadBalancer
  # type: ClusterIP
  ports:
  - port: 80  
    targetPort: 9000  
  selector:
    app: sonarqube
---



# admin -p admin123

# squ_65457430d70defd04c34599fefec24e9adc99ef5

# http://master.jenkins.infinityfreeapp.com/sonarqube-webhook/